### PR TITLE
WIP: creating zh-Hant localization

### PR DESCRIPTION
**Pull request by pan93412**

### CODE REVIEW

**Review by x74353 — APPROVED** [review]

**Comment by pan93412** [comment]
@x74353 It is incompleted 😅! I didn't finish it and it had left a lot of untranslated strings which affected UX a lot 😢. Could you help me not build this locale until I or other contributors completed it? Thanks very lot! 😆

截圖 2021-05-30 上午12 12 10

**Comment by pan93412** [comment]
I just completed the "Settings" part. I was busying those days so I didn't continue translating it these days. Sorry :-(

截圖 2021-05-30 上午12 14 11

**Comment by x74353** [comment]
@pan93412 That's ok. I saw that it is WIP. I accepted the progress. Feel free to create another pull request when you are ready. I will not include this in a release until complete and tested. Thanks so much for your hard work on this!  :)

**Comment by pan93412** [comment]
> @pan93412 That's ok. I saw that it is WIP. I accepted the progress. Feel free to create another pull request when you are ready. I will not include this in a release until complete and tested. Thanks so much for your hard work on this! :)

Thanks a lot! I'll continue it after I took care on my things. :-)

**Pull request merged**
